import type { Pub } from "@/components/book";

export const PRODUCT_CATALOG: Pub[] = [
  {
    id: 1,
    title: "The Husband's Postpartum Handbook",
    slug: "the-husbands-postpartum-handbook",
    subtitle: "The guide every husband wishes he had before baby arrived.",
    description: "A practical guide to supporting your wife, strengthening your marriage, and thriving together after childbirth.",
    longDescription: "Understand the physical, emotional, and mental changes after childbirth, rebuild emotional connection, support intimacy with patience, and recognize when professional help may be needed. Includes five bonus guides for new fathers and couples.",
    authorName: "Angele Nena",
    category: "Parenting & Family",
    price: "0",
    currency: "USD",
    coverColor: "#171717",
    coverImageUrl: "/images/publications/husbands-postpartum-handbook-cover.jpg",
    tocImageUrl: "/images/publications/husbands-postpartum-handbook-toc.jpg",
    spreadImageUrl: "/images/publications/husbands-postpartum-handbook-spread.jpg",
    bonuses: JSON.stringify([
      { title: "30-Day Marriage Reconnection Challenge", description: "Small daily actions to help couples reconnect." },
      { title: "100 Encouraging Things Every Husband Can Say After Baby", description: "Supportive phrases for the postpartum season." },
      { title: "Understanding Postpartum Depression & Anxiety", description: "Warning signs and compassionate support guidance." },
      { title: "52 Simple Date Nights for New Parents", description: "Meaningful ideas for busy new parents." },
      { title: "The New Dad's Survival Guide", description: "Practical advice for navigating fatherhood." },
    ]),
    buyLink: "https://selar.com/2421e273f2",
    sampleLink: "#details",
    isFree: false,
  },
  {
    id: 2,
    title: "The Old Midwife's Tearing Secret",
    slug: "the-old-midwifes-tearing-secret",
    subtitle: "Breaking the cycle of intimacy pain, tearing, and infection after birth.",
    description: "A gentle postpartum recovery guide for understanding healing, reducing discomfort, and knowing when to seek medical care.",
    longDescription: "Learn practical postpartum self-care, nutrition for tissue healing, recovery monitoring, appointment preparation, and important warning signs. This educational guide supports informed recovery but does not replace care from a doctor, midwife, or other healthcare professional.",
    authorName: "Digital Angel",
    category: "Health & Wellness",
    price: "0",
    currency: "USD",
    coverColor: "#5b2c35",
    coverImageUrl: "/images/publications/old-midwifes-tearing-secret-cover.jpg",
    tocImageUrl: "/images/publications/old-midwifes-tearing-secret-toc.jpg",
    spreadImageUrl: "/images/publications/old-midwifes-tearing-secret-spread.jpg",
    bonuses: JSON.stringify([
      { title: "Foods That Support Tissue Healing After Birth", description: "Nutrients and meal ideas for postpartum recovery." },
      { title: "Questions Every Woman Should Ask Her Gynecologist", description: "Prepare for more confident medical appointments." },
      { title: "Postpartum Recovery Checklist", description: "A printable week-by-week healing guide." },
      { title: "Signs You Need Medical Attention After Childbirth", description: "Important symptoms that require timely care." },
    ]),
    buyLink: "https://selar.com/z8s757x68o",
    sampleLink: "#details",
    isFree: false,
  },
  {
    id: 3,
    title: "Love After Baby",
    slug: "love-after-baby",
    subtitle: "A gentle 14-day postpartum reset for confidence, desire, and intimacy.",
    description: "A compassionate daily guide to rebuilding confidence, reconnecting with yourself, and strengthening your marriage after childbirth.",
    longDescription: "Take small, realistic steps toward body confidence, emotional connection, healthy communication, and self-care. This 14-day reset includes eight companion bonuses, including a nursing mother's self-care guide, a touch reconnection framework, trackers, worksheets, and postpartum FAQs.",
    authorName: "Digital Angel",
    category: "Relationships",
    price: "14.99",
    currency: "USD",
    coverColor: "#8a4b45",
    coverImageUrl: "/images/publications/love-after-baby-cover.jpg",
    tocImageUrl: "/images/publications/love-after-baby-toc.jpg",
    spreadImageUrl: "/images/publications/love-after-baby-spread.jpg",
    bonuses: JSON.stringify([
      { title: "The Nursing Mother's Self-Care Guide", description: "Practical rest, nourishment, and self-care tips." },
      { title: "Dear Hubby", description: "A guide for husbands to understand and reconnect." },
      { title: "Understanding Postpartum Depression & Anxiety", description: "Warning signs and professional-support guidance." },
      { title: "The Touch Reconnection Ladder", description: "A gentle framework for rebuilding closeness." },
      { title: "Body Confidence Tracker", description: "Daily habits and reflection prompts." },
      { title: "Am I Normal? Private Postpartum FAQ", description: "Answers to common postpartum questions." },
      { title: "Daily Action Sheets & Progress Checklists", description: "Worksheets for consistency and progress." },
      { title: "30-Day Reconnection Tracker", description: "Continue building healthy habits after the reset." },
    ]),
    buyLink: "https://selar.com/a12e1726ko",
    sampleLink: "#details",
    isFree: false,
  },
];

export function getProduct(slug: string) {
  return PRODUCT_CATALOG.find((product) => product.slug === slug) ?? null;
}
